name: Build Go Binaries

on:
  pull_request:
  release:
    types: [published]

jobs:
  Build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        platform: [darwin-amd64, darwin-arm64, freebsd-amd64, linux-amd64, linux-arm64, windows-amd64]
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v4
      with:
        go-version: '1.22'
    - name: Set ENV
      run: |
        echo "GOOS=$(echo ${{ matrix.platform }} | cut -d'-' -f1)" >> $GITHUB_ENV
        echo "GOARCH=$(echo ${{ matrix.platform }} | cut -d'-' -f2)" >> $GITHUB_ENV
    - name: Install dependencies
      run: go get .
    - name: Build
      run: go build -v ./...
    - name: Test
      run: go test
    - name: Attach Binaries to release
      if: github.event_name == 'release'
      run: echo "TODO"

  Check-Build:
    if: ${{ always() }}
    runs-on: ubuntu-latest
    needs:
      - Build
    steps:
      - run: |
          result="${{ needs.Build.result }}"
          if [[ $result == "success" || $result == "skipped" ]]; then
            exit 0
          else
            exit 1
          fi
