name: Build Go Binaries

on:
  pull_request:
  release:
    types: [published]

jobs:
  Build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    timeout-minutes: 1
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version: '1.22'
        cache: false
    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: Install pip dependencies
      run: pip install -r .github/assets/Requirements.txt
    - name: Install dependencies
      run: go get .
    - name: Build
      run: go build -o go-sfs-${{ matrix.os }} -v ./main.go
    - name: Test
      run: go test
    - name: E2E Test
      run: python3 .github/assets/end_to_end_test.py go-sfs-${{ matrix.os }}
    - uses: actions/create-github-app-token@v1
      if: github.event_name == 'release'
      id: generate-token
      with:
        app-id: ${{ secrets.APP_ID }}
        private-key: ${{ secrets.APP_PRIVATE_KEY }}
    - name: Attach Binaries to release
      if: github.event_name == 'release'
      env:
        GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}
      run:
        gh release upload ${{ github.event.release.tag_name }} go-sfs-${{ matrix.os }}

  Check-Go-Build:
    if: ${{ always() }}
    runs-on: ubuntu-latest
    needs:
      - Build
    steps:
      - run: |
          result="${{ needs.Build.result }}"
          if [[ $result == "success" || $result == "skipped" ]]; then
            exit 0
          else
            exit 1
          fi
