name: Build Go Binaries

on:
  pull_request:
  release:
    types: [published]

jobs:
  Build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v4
      with:
        go-version: '1.22'
    - name: Install dependencies
      run: go get .
    - name: Build
      run: go build -v ./...
    - name: Test
      run: go test
    - name: Attach Binaries to release
      if: github.event_name == 'release'
      run: echo "TODO"

  Check-Build:
    if: ${{ always() }}
    runs-on: ubuntu-latest
    needs:
      - Build
    steps:
      - run: |
          result="${{ needs.Build.result }}"
          if [[ $result == "success" || $result == "skipped" ]]; then
            exit 0
          else
            exit 1
          fi
