name: "Release"
on:
  workflow_dispatch:

jobs:
  release:
    name: "Release"
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Matrix-Jobs
        id: get-version
        run: |
          echo "version=$(grep FROM ./Dockerfile | head -n1 | cut -d':' -f2 | cut -d' ' -f1 | xargs)" >> $GITHUB_OUTPUT
      - uses: actions/create-github-app-token@v1
        id: generate-token
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
      - name: Create Release
        if: github.event_name == 'release'
        env:
          GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}
        run:
          gh release create ${{ steps.get-version.outputs.version }} --generate-notes