name: "Release"
on:
  workflow_dispatch:
    inputs:
      bumpstep:
        description: 'Version bump: major, minor, bug'
        required: true
        default: 'minor'
        type: choice
        options:
          - major
          - minor
          - bug
jobs:
  release:
    name: "Release"
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - id: version
        run: |
          LATEST_TAG=$(curl -s "https://api.github.com/repos/${GITHUB_REPOSITORY}/releases/latest" | jq -r '.name')
          if [[ ${LATEST_TAG} == 'null' ]]; then
            LATEST_TAG='0.0.0'
          fi
          URL='https://gist.githubusercontent.com/mietzen/cd33efb65f91619201a45ac50dcfc29e/raw/bump-version'
          echo "version=v$(wget -qO - ${URL} | bash -s ${LATEST_TAG} ${{ inputs.bumpstep }})" >> $GITHUB_OUTPUT
      - uses: actions/create-github-app-token@v1
        id: generate-token
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}
        run:
          gh release create ${{ steps.version.outputs.version }} --generate-notes